apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "atlassian-confluence.fullname" . }}
  labels:
    {{ template "common.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "atlassian-confluence.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "atlassian-confluence.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        {{ template "containers.image" . }}
          env:
            {{ template "env.jvm" . }}
            {{ template "env.additional" . }}
            {{- if .Values.proxy.enabled }}
            - name: CATALINA_CONNECTOR_PROXYNAME
              value: {{ .Values.proxy.host | quote }}
            - name: CATALINA_CONNECTOR_PROXYPORT
              value: {{ .Values.proxy.port }}
            - name: CATALINA_CONNECTOR_SCHEME
              value: {{ .Values.proxy.scheme | quote }}
            - name: CATALINA_CONNECTOR_SECURE
              value: {{ .Values.proxy.path | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - name: controller
              containerPort: 8091
              protocol: TCP
          {{ template "health.httpProbes" . }}
          volumeMounts:
          - mountPath: /var/atlassian/application-data/confluence
            name: {{ template "atlassian-confluence.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: {{ template "atlassian-confluence.fullname" . }}
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "atlassian-confluence.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
